export const ROLES = {
  FAN: 'FAN',
  CLUB_ADMIN: 'CLUB_ADMIN',
  LEAGUE_ADMIN: 'LEAGUE_ADMIN',
  UNION_ADMIN: 'UNION_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
  REFEREE: 'REFEREE',
  TICKETING_OFFICER: 'TICKETING_OFFICER',
  SPONSOR: 'SPONSOR',
};
